### ISSUE TITLE
拖拽窗口大小报错 System.DllNotFoundException: Unable to load DLL 'shcore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)

### ISSUE THREAD

**Issue by fireattack** [HMBSbige/BilibiliLiveRecordDownLoader#198]
OS: Win7
Version： 3.9.0.0

```
[2022-01-06 02:36:13] [Information] [21359933] 开始录制
[2022-01-06 02:36:14] [Information] [21359933] 正在连接弹幕服务器 wss://tx-live-dmcmt-sv-01.chat.bilibili.com:443/sub
[2022-01-06 02:36:14] [Information] [21359933] 连接弹幕服务器成功
[2022-01-06 02:36:14] [Information] [21359933] 进房成功
[2022-01-06 08:54:58] [Fatal] 未捕获异常
System.DllNotFoundException: Unable to load DLL 'shcore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at SourceChord.FluentWPF.AcrylicWindow.GetDpiForMonitor(IntPtr hMonitor, MONITOR_DPI_TYPE dpiType, UInt32& dpiX, UInt32& dpiY)
   at SourceChord.FluentWPF.AcrylicWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by fireattack** [comment]
v3.8.2 无此问题

**Comment by HMBSbige** [comment]
请问是稳定复现的吗？
如果不能复现的 DllNotFoundException 往往是 https://github.com/HMBSbige/BilibiliLiveRecordDownLoader/discussions/93#discussioncomment-1220238

**Comment by fireattack** [comment]
稳定复现，应该是win7的问题。

搜了下似乎win7根本没有这个dll，然后.net 6版的FluentWPF的GetDpiForMonitor会调用到他（但是很奇怪.net 5不会）。

https://github.com/sourcechord/FluentWPF/issues/157

值不值得修就看你了，毕竟也没几个人用win7了估计……

辛苦！

**Comment by HMBSbige** [comment]
不过这种确实不是很重要，之后 UI 应该是要重写的（win7应该是不再支持了）
