### ISSUE TITLE
3.5.1~3.7.1版本出现的一个报错

### ISSUE THREAD

**Issue by SekiBetu** [HMBSbige/BilibiliLiveRecordDownLoader#85]
```C#
[Error] 刷新房间状态出错
System.Net.Http.HttpRequestException: Response status code does not indicate success: 412 (Precondition Failed).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at BilibiliApi.Clients.BilibiliApiClient.GetJsonAsync[T](String url, CancellationToken token) in D:\a\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader.BilibiliApi\Clients\BilibiliApiClient.cs:line 35
   at BilibiliApi.Clients.BilibiliApiClient.GetRoomInfoAsync(Int64 roomId, CancellationToken token) in D:\a\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader.BilibiliApi\Clients\RoomInfoApi.cs:line 113
   at BilibiliApi.Clients.BilibiliApiClient.GetRoomInfoDataAsync(Int64 roomId, CancellationToken token) in D:\a\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader.BilibiliApi\Clients\RoomInfoApi.cs:line 124
   at BilibiliLiveRecordDownLoader.Models.RoomStatus.GetRoomInfoDataAsync(Boolean isThrow, CancellationToken token) in D:\a\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\Models\RoomStatus.cs:line 168
   at BilibiliLiveRecordDownLoader.Models.RoomStatus.RefreshStatusAsync(CancellationToken token) in D:\a\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\Models\RoomStatus.cs:line 201
[2021-05-17 01:38:58] [Error] 刷新房间状态出错
```

```C#
[Error] 添加房间出错
System.Net.Http.HttpRequestException: Response status code does not indicate success: 412 (Precondition Failed).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at BilibiliApi.Clients.BilibiliApiClient.GetJsonAsync[T](String url, CancellationToken token) in D:\a\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader.BilibiliApi\Clients\BilibiliApiClient.cs:line 41
   at BilibiliApi.Clients.BilibiliApiClient.GetRoomInfoAsync(Int64 roomId, CancellationToken token) in D:\a\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader.BilibiliApi\Clients\RoomInfoApi.cs:line 113
   at BilibiliApi.Clients.BilibiliApiClient.GetRoomInfoDataAsync(Int64 roomId, CancellationToken token) in D:\a\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader.BilibiliApi\Clients\RoomInfoApi.cs:line 124
   at BilibiliLiveRecordDownLoader.Models.RoomStatus.GetRoomInfoDataAsync(Boolean isThrow, CancellationToken token) in D:\a\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\Models\RoomStatus.cs:line 168
   at BilibiliLiveRecordDownLoader.ViewModels.StreamRecordViewModel.AddRoomAsync(CancellationToken token) in D:\a\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\BilibiliLiveRecordDownLoader\ViewModels\StreamRecordViewModel.cs:line 146
```

![image](https://user-images.githubusercontent.com/38283893/118407420-3b95b400-b6b3-11eb-9d87-fe052bff8c87.png)
![image](https://user-images.githubusercontent.com/38283893/118407434-4ea88400-b6b3-11eb-8fb3-f1d752137d76.png)

看到这个报错的信息，发现，我电脑上没D盘，是不是代码里写死了是D盘

**Comment by SekiBetu** [comment]
3.5.0版本刚才用着正常，现在也炸了，我继续在找原因

**Comment by HMBSbige** [comment]
412 是B站的请求限制，看截图应该是你房间太多导致的

**Comment by SekiBetu** [comment]
好像是这样，睡了一晚上，早上起来没问题了
